import 'dart:convert';
import 'dart:math' as math;
import 'dart:io';
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

const dataUrl = 'https://raw.githubusercontent.com/weatherstationsegamat-lgtm/WeatherStationSegamat/main/data.json';

void main() => runApp(const WeatherApp());

class WeatherApp extends StatefulWidget { const WeatherApp({super.key}); @override State<WeatherApp> createState()=>_WeatherAppState(); }
class _WeatherAppState extends State<WeatherApp> {
  ThemeMode theme=ThemeMode.system; bool en=true;
  @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'SG Segamat Weather',themeMode:theme,theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),darkTheme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo,brightness:Brightness.dark),home:Home(en:onLang(),dark:onTheme()));
  VoidCallback onLang()=>()=>setState(()=>en=!en); VoidCallback onTheme()=>()=>setState(()=>theme=theme==ThemeMode.dark?ThemeMode.light:ThemeMode.dark);
}

class Home extends StatefulWidget { final bool en; final VoidCallback dark,onLang; const Home({super.key,required this.en,required this.dark,required this.onLang}); @override State<Home> createState()=>_HomeState(); }
class _HomeState extends State<Home> {
  List<Map<String,dynamic>> r=[]; bool loading=true; String? error; int page=0; String range='24h';
  final enabled=<String,bool>{'Temperature':true,'UV':true,'Humidity':true,'Battery':true,'Offline':true};
  final th=<String,double>{'High temperature':35,'Low temperature':20,'High UV':8,'Low battery':3.3,'High humidity':90};
  String tx(String a,String b)=>widget.en?a:b; double numv(Map x,String k)=>(x[k] as num?)?.toDouble()??double.nan; String f(double x,[int d=1])=>x.isNaN?'--':x.toStringAsFixed(d);
  Map<String,dynamic> get latest=>r.isEmpty?<String,dynamic>{}:r.last;
  @override void initState(){super.initState();load();}
  Future<void> load() async { if(mounted)setState(()=>loading=true); try { final q=await http.get(Uri.parse('$dataUrl?v=${DateTime.now().millisecondsSinceEpoch}')); if(q.statusCode!=200)throw Exception('HTTP ${q.statusCode}'); final x=jsonDecode(q.body); if(x is! List||x.isEmpty)throw Exception('No weather records'); final z=x.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList(); if(mounted)setState(()=>r=z); } catch(e){if(mounted)setState(()=>error=e.toString());} finally {if(mounted)setState(()=>loading=false);} }
  DateTime? dt(Map x)=>DateTime.tryParse(x['timestamp']?.toString()??'');
  bool online(){final d=dt(latest);return d!=null&&DateTime.now().difference(d).inMinutes<=10;}
  List<Map<String,dynamic>> data(){if(r.isEmpty)return[];final mins={'1h':60,'6h':360,'24h':1440,'7d':10080,'30d':43200}[range]??1440;final last=dt(latest);if(last==null)return r;return r.where((x){final d=dt(x);return d!=null&&last.difference(d).inMinutes<=mins;}).toList();}
  List<double> vals(String k)=>data().map((x)=>numv(x,k)).where((x)=>!x.isNaN).toList();
  double av(String k){final v=vals(k);return v.isEmpty?double.nan:v.reduce((a,b)=>a+b)/v.length;} double mn(String k){final v=vals(k);return v.isEmpty?double.nan:v.reduce(math.min);} double mx(String k){final v=vals(k);return v.isEmpty?double.nan:v.reduce(math.max);}
  double dew(double t,double h){if(t.isNaN||h.isNaN||h<=0)return double.nan;const a=17.62,b=243.12;final g=math.log(h/100)+a*t/(b+t);return b*g/(a-g);}
  double heat(double c,double h){if(c.isNaN||h.isNaN)return double.nan;final f=c*9/5+32;if(f<80)return c;final z=-42.379+2.04901523*f+10.14333127*h-.22475541*f*h-.00683783*f*f-.05481717*h*h+.00122874*f*f*h+.00085282*f*h*h-.00000199*f*f*h*h;return(z-32)*5/9;}
  String dir(double x){if(x.isNaN)return'--';const a=['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'];return a[((x+11.25)~/22.5)%16];}
  @override Widget build(BuildContext c){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));if(error!=null)return Scaffold(appBar:AppBar(title:const Text('SG Segamat Weather')),body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.cloud_off,size:60),Text('Data unavailable'),FilledButton(onPressed:load,child:Text('Retry'))])));final ps=[dashboard(),history(),wind(),alerts(),tools()];return Scaffold(appBar:AppBar(title:const Text('SG Segamat Weather'),actions:[IconButton(onPressed:widget.onLang,icon:const Icon(Icons.translate)),IconButton(onPressed:widget.dark,icon:const Icon(Icons.brightness_6)),IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:RefreshIndicator(onRefresh:load,child:ps[page]),bottomNavigationBar:NavigationBar(selectedIndex:page,onDestinationSelected:(i)=>setState(()=>page=i),destinations:[NavigationDestination(icon:Icon(Icons.dashboard),label:tx('Live','Live')),NavigationDestination(icon:Icon(Icons.show_chart),label:tx('History','Sejarah')),NavigationDestination(icon:Icon(Icons.explore),label:tx('Wind','Angin')),NavigationDestination(icon:Icon(Icons.notifications),label:tx('Alerts','Amaran')),NavigationDestination(icon:Icon(Icons.more_horiz),label:tx('More','Lagi'))]));}
  Widget status()=>Chip(label:Text(online()?'● ONLINE':'● OFFLINE'),avatar:Icon(Icons.circle,size:10,color:online()?Colors.green:Colors.red));
  Widget cardMetric(IconData i,String s,double v,String u)=>Card(child:Padding(padding:const EdgeInsets.all(13),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i),const Spacer(),Text(s,style:const TextStyle(color:Colors.grey)),Text('${f(v)}$u',style:const TextStyle(fontSize:19,fontWeight:FontWeight.bold))])));
  Widget dashboard(){final t=numv(latest,'temperature'),h=numv(latest,'humidity'),w=numv(latest,'wind_direction'),u=numv(latest,'uv'),p=numv(latest,'pressure'),l=numv(latest,'visible_light'),a=numv(latest,'altitude'),b=numv(latest,'battery_v');return ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Expanded(child:Text('Sungai Segamat, Johor',style:TextStyle(fontWeight:FontWeight.bold))),status()]),const SizedBox(height:16),Text('${f(t)}°C',style:const TextStyle(fontSize:48,fontWeight:FontWeight.w700)),Text(tx('Current temperature','Suhu semasa')),Text('${tx('Wind','Angin')}: ${f(w)}° ${dir(w)}'),Text('${tx('Last updated','Kemas kini')}: ${latest['timestamp']??'--'} GMT+8')]))),const SizedBox(height:10),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,mainAxisSpacing:8,crossAxisSpacing:8,childAspectRatio:1.55,children:[cardMetric(Icons.water_drop,tx('Humidity','Kelembapan'),h,'%'),cardMetric(Icons.explore,tx('Wind direction','Arah angin'),w,'° ${dir(w)}'),cardMetric(Icons.wb_sunny,'UV',u,''),cardMetric(Icons.speed,tx('Pressure','Tekanan'),p,' hPa'),cardMetric(Icons.light_mode,tx('Visible light','Cahaya'),l,''),cardMetric(Icons.terrain,tx('Altitude','Altitud'),a,' m'),cardMetric(Icons.battery_full,tx('Battery','Bateri'),b,' V')]),const SizedBox(height:10),sectionChart('Temperature','temperature','°C'),Card(child:ListTile(leading:const Icon(Icons.analytics),title:Text(tx('Heat index / dew point','Indeks haba / takat embun')),subtitle:Text('${f(heat(t,h))}°C / ${f(dew(t,h))}°C')))]);}
  Widget sectionChart(String title,String key,String unit)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('$title $unit',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:18)),const SizedBox(height:8),chart(key,190)])));
  Widget chart(String key,double h){final d=data();final spots=<FlSpot>[];for(int i=0;i<d.length;i++){final v=numv(d[i],key);if(!v.isNaN)spots.add(FlSpot(i.toDouble(),v));}if(spots.length<2)return SizedBox(height:h,child:Center(child:Text(tx('Not enough history','Sejarah tidak mencukupi'))));return SizedBox(height:h,child:LineChart(LineChartData(minX:0,maxX:math.max(1,d.length-1).toDouble(),gridData:const FlGridData(show:true),titlesData:const FlTitlesData(show:false),borderData:FlBorderData(show:false),lineBarsData:[LineChartBarData(spots:spots,isCurved:true,barWidth:3,dotData:const FlDotData(show:false))])));}
  Widget history(){final items=[['temperature','Temperature','°C'],['humidity','Humidity','%'],['pressure','Pressure','hPa'],['uv','UV',''],['visible_light','Visible light',''],['battery_v','Battery','V']];return ListView(padding:const EdgeInsets.all(16),children:[Text(tx('History & graphs','Sejarah & graf'),style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:10),SegmentedButton<String>(segments:const[ButtonSegment(value:'1h',label:Text('1h')),ButtonSegment(value:'6h',label:Text('6h')),ButtonSegment(value:'24h',label:Text('24h')),ButtonSegment(value:'7d',label:Text('7d')),ButtonSegment(value:'30d',label:Text('30d'))],selected:{range},onSelectionChanged:(s)=>setState(()=>range=s.first)),...items.map((x)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${x[1]} ${x[2]}',style:const TextStyle(fontWeight:FontWeight.bold)),chart(x[0],160),Wrap(spacing:5,children:[Chip(label:Text('Min ${f(mn(x[0]))}')),Chip(label:Text('Avg ${f(av(x[0]))}')),Chip(label:Text('Max ${f(mx(x[0]))}'))])]))))]));}
  Widget wind(){final counts=<String,int>{};for(final x in data()){final d=dir(numv(x,'wind_direction'));if(d!='--')counts[d]=(counts[d]??0)+1;}final sorted=counts.entries.toList()..sort((a,b)=>b.value.compareTo(a.value));final w=numv(latest,'wind_direction');return ListView(padding:const EdgeInsets.all(16),children:[Text(tx('Wind analysis','Analisis angin'),style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[Text(dir(w),style:const TextStyle(fontSize:40,fontWeight:FontWeight.bold)),Text('${f(w)}°'),const SizedBox(height:15),CustomPaint(size:const Size(220,220),painter:Compass(w))]))),Card(child:ListTile(title:Text(tx('Dominant direction','Arah dominan')),subtitle:Text(sorted.isEmpty?'--':'${sorted.first.key} (${sorted.first.value} records)'))),Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(tx('Wind rose','Wind rose'),style:const TextStyle(fontWeight:FontWeight.bold)),...sorted.map((e)=>Row(children:[SizedBox(width:40,child:Text(e.key)),Expanded(child:LinearProgressIndicator(value:e.value/math.max(1,data().length))),const SizedBox(width:8),Text('${e.value}')]))])),const Card(child:ListTile(leading:Icon(Icons.speed),title:Text('Wind speed'),subtitle:Text('Not provided by current station payload.'))]);}
  Widget alerts(){final t=numv(latest,'temperature'),u=numv(latest,'uv'),h=numv(latest,'humidity'),b=numv(latest,'battery_v');final a=<String>[];if(enabled['Temperature']!&&(!t.isNaN&&(t>=th['High temperature']!||t<=th['Low temperature']!)))a.add('Temperature threshold');if(enabled['UV']!&&!u.isNaN&&u>=th['High UV']!)a.add('High UV');if(enabled['Humidity']!&&!h.isNaN&&h>=th['High humidity']!)a.add('High humidity');if(enabled['Battery']!&&!b.isNaN&&b>0&&b<=th['Low battery']!)a.add('Low battery');if(enabled['Offline']!&&!online())a.add('Offline / stale data');return ListView(padding:const EdgeInsets.all(16),children:[Text(tx('Alerts & thresholds','Amaran & ambang'),style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),Card(child:ListTile(leading:Icon(a.isEmpty?Icons.check_circle:Icons.warning),title:Text(a.isEmpty?tx('No active alerts','Tiada amaran aktif'):'${a.length} active alerts'),subtitle:Text(a.isEmpty?tx('Station looks normal.','Stesen kelihatan normal.') : a.join(' • ')))),...enabled.keys.map((k)=>SwitchListTile(title:Text(k),value:enabled[k]!,onChanged:(v)=>setState(()=>enabled[k]=v)))];}
  Widget tools()=>ListView(padding:const EdgeInsets.all(16),children:[Text(tx('Tools & AI','Alat & AI'),style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),Card(child:ListTile(leading:const Icon(Icons.psychology),title:const Text('Ask SG Segamat AI'),subtitle:Text(tx('Answers use the live station data.','Jawapan menggunakan data stesen semasa.')),onTap:ai)),Card(child:ListTile(leading:const Icon(Icons.file_download),title:Text(tx('Export & share CSV','Eksport & kongsi CSV')),subtitle:Text('${data().length} ${tx('records in $range','rekod dalam $range')}'),onTap:csv)),Card(child:ListTile(leading:const Icon(Icons.calendar_month),title:Text(tx('Daily / weekly report','Laporan harian / mingguan')),subtitle:Text('${tx('24h average','Purata 24j')}: ${f(av('temperature'))}°C • ${tx('High','Tinggi')}: ${f(mx('temperature'))}°C • ${tx('Low','Rendah')}: ${f(mn('temperature'))}°C'))),Card(child:const ListTile(leading:Icon(Icons.location_city),title:Text('Stations'),subtitle:Text('SG_Segamat • additional sources can be added later'))),Card(child:ListTile(leading:const Icon(Icons.map),title:Text(tx('Station map','Peta stesen')),subtitle:Text(tx('Coordinates are not present in current data.','Koordinat tiada dalam data semasa.')))),const Card(child:ListTile(leading:Icon(Icons.info),title:Text('Phases 1–9'),subtitle:Text('Live • Graphs • Wind • Alerts • Data • UI • AI • Multi-station • Analytics'))]);
  Future<void> ai(){final t=numv(latest,'temperature'),h=numv(latest,'humidity'),u=numv(latest,'uv'),w=numv(latest,'wind_direction');return showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('SG Segamat AI'),content:Text('${tx('Live station analysis','Analisis stesen semasa')}\n\nTemperature: ${f(t)}°C\nHumidity: ${f(h)}%\nUV: ${f(u)}\nWind: ${dir(w)} (${f(w)}°)\n\n${t>=th['High temperature']!?tx('It is hot; take heat precautions.','Keadaan panas; berjaga-jaga dengan haba.'):tx('Temperature is below the high threshold.','Suhu di bawah ambang tinggi.')}\n${tx('24h average temperature','Purata suhu 24j')}: ${f(av('temperature'))}°C\n${tx('Heat index','Indeks haba')}: ${f(heat(t,h))}°C\n${tx('Dew point','Takat embun')}: ${f(dew(t,h))}°C'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('OK'))]));}
  Future<void> csv() async {final fields=['station_name','timestamp','temperature','humidity','wind_direction','uv','visible_light','pressure','altitude','battery_v'];final lines=[fields.join(','),...data().map((x)=>fields.map((k)=>'"${(x[k]??'').toString().replaceAll('"','""')}"').join(','))];final d=await getTemporaryDirectory();final file=File('${d.path}/SG_Segamat_weather_$range.csv');await file.writeAsString(lines.join('\n'));await Share.shareXFiles([XFile(file.path)],text:'SG Segamat Weather CSV ($range)');}
}
class Compass extends CustomPainter {final double d;Compass(this.d);@override void paint(Canvas c,Size s){final m=Offset(s.width/2,s.height/2),r=s.shortestSide/2-10,p=Paint()..style=PaintingStyle.stroke..strokeWidth=2;c.drawCircle(m,r,p);const l=['N','E','S','W'];for(int i=0;i<4;i++){final a=i*math.pi/2,pos=m+Offset(math.sin(a)*(r-20),-math.cos(a)*(r-20));final q=TextPainter(text:TextSpan(text:l[i],style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16)),textDirection:TextDirection.ltr)..layout();q.paint(c,pos-Offset(q.width/2,q.height/2));}if(!d.isNaN){final a=d*math.pi/180;c.drawLine(m,m+Offset(math.sin(a)*(r-35),-math.cos(a)*(r-35)),Paint()..strokeWidth=5..strokeCap=StrokeCap.round);}}@override bool shouldRepaint(covariant Compass o)=>o.d!=d;}
